---

- name: burp | web UI | packages
  tags:
    - package
  package:
    name:
      - python-pip
      - libpython-dev
      - libffi-dev
      - libssl-dev

- name: burp | web UI | packages (pip)
  tags:
    - package
  pip:
    name:
      - markupsafe
      - functools32
      - "burp-ui[sql]"
  notify: restart burp-ui

- name: burp | web UI | config
  tags:
    - config
  template:
    src: burpui.cfg.j2
    dest: "{{ burp_conf_dir }}/burpui.cfg"
  notify: restart burp-ui

- name: burp | web UI | logrotate
  tags:
    - logrotate
  copy:
    dest: "/etc/logrotate.d/burp-ui"
    content: "{{ burpui_log }} {}"

- name: burp | web UI | nginx config
  vars:
    site: burp
  include_role:
    name: nginx
    tasks_from: site.yml

- name: burp | web UI | systemd service
  tags:
    - systemd
  template:
    src: burp-ui.service.j2
    dest: /etc/systemd/system/burp-ui.service
  notify: restart burp-ui

- name: burp | web UI | service
  tags:
    - service
  service:
    name: burp-ui
    state: started
    enabled: yes
