---

- name: Burp web UI | packages
  tags:
    - package
  package:
    name: "{{ item }}"
  with_items:
    - python-pip
    - libpython-dev
    - libffi-dev
    - libssl-dev

- name: Burp web UI | packages (pip)
  tags:
    - package
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - markupsafe
    - functools32
    - "burp-ui[sql]"
  notify: restart burp-ui

- name: Burp web UI | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ burp_conf_dir }}/{{ item }}"
  with_items:
    - burpui.cfg
  notify: restart burp-ui

- name: Burp web UI | logrotate
  tags:
    - logrotate
  copy:
    dest: "/etc/logrotate.d/burp-ui"
    content: "{{ burpui_log }} {}"

- name: Burp web UI | nginx config
  include_role:
    name: nginx
    tasks_from: site.yml
  with_items: burp

- name: Burp web UI | systemd service
  tags:
    - systemd
  template:
    src: burp-ui.service.j2
    dest: /etc/systemd/system/burp-ui.service
  notify: restart burp-ui

- name: Burp web UI | service
  tags:
    - service
  service:
    name: burp-ui
    state: started
