---

- name: burp | client | directories
  tags:
  - dirs
  file:
    path: "{{ burp_conf_dir }}/{{ item }}"
    state: directory
    mode: 0750
  with_items:
  - keys
  - upgrade

- name: burp | client | dependencies
  tags:
  - package
  package:
    name: librsync-dev

# Binaries compiled on a Debian host from git:
# sudo apt-get install make pkg-config check g++ librsync-dev libz-dev libssl-dev uthash-dev libyajl-dev
# sudo apt-get install autoconf automake libtool
# git clone https://github.com/grke/burp && cd burp/
# git checkout {{ burp_version }}
# autoreconf -fis
# ./configure --prefix=/usr --sysconfdir=/etc/burp --localstatedir=/var
# make

- name: burp | client | executables
  tags:
  - binary
  copy:
    src: "bin/{{ burp_version }}/{{ ansible_architecture }}/{{ item }}"
    dest: /usr/sbin/
    mode: 0755
  with_items:
  - burp
  - vss_strip

- name: burp | client | scripts
  copy:
    src: burp_ca
    dest: /usr/sbin/
    mode: 0755

- name: burp | client | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ burp_conf_dir }}/{{ item }}"
    mode: 0640
  with_items:
    - burp.conf

- name: burp | client | cron
  tags:
  - cron
  cron:
    name: 'burp cron'
    cron_file: burp
    user: root
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: '*/12'
    job: '/usr/sbin/burp -Q -a t'
